//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Services
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public long ID { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public Nullable<System.DateTime> Birthday { get; set; }
        public Nullable<int> Sex { get; set; }
        public Nullable<int> Course { get; set; }
        public Nullable<int> Group { get; set; }
    
        public virtual Sex Sex1 { get; set; }
    }
}
